# Generated by Django 3.2.3 on 2021-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KHUgle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
