# Generated by Django 3.2.2 on 2021-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
