# Generated by Django 3.2.3 on 2021-05-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
